name: golangci
on:
  pull_request:
    branches:
      - main
jobs:
  golint:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ macos-latest, ubuntu-latest ]
    name: lint ${{ matrix.go-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.43.0
  gotest:
    strategy:
      matrix:
        go-version: [ 1.17.x ]
        os: [ macos-latest, ubuntu-latest ]
    name: unittest ${{ matrix.go-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: go-test
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v ./bigip
